name: Generate PDF
on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: >
          sudo apt-get install pandoc
          sudo apt-get install wkhtmltopdf
      - name: Generate PDF
        run: >
          pandoc $(find lezioni -name "*.md" | sort -n ) \
            --pdf-engine=wkhtmltopdf -o a.pdf
